export const homeObjOne = {
    id: 'setup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Setup',
    headLine: "Make Sure Toastify is Downloaded.",
    description: "Toastify must be running while Spotify Hand Detection is up for it to work.  Leave Toastify's HotKey Settings on Default. You Can Go to Toastify's Page Here.",
    buttonLabel: 'Link to Download Toastify',
    imgStart: false,
    img: require('../../images/blueSpotify.png'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};
export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'discover poop Poop',
    headLine: 'Ulimited Poop with Zero Fees',
    description: 'Download this cool thing that allows you to control music with your hands',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/naruto.jpg'),
    alt: 'pony',
    dark: false,
    primary: false,
    darkText: true,
};